In [3]:
from PIL import Image
import os
import cv2
import numpy as np

<h2> Import of Libraries </h2>  

In [4]:
# Função para ler as imagens de uma pasta e retornar um dicionário
def ler_imagens_de_pasta(folder_name):
    images = {}
    print(f"Imagens do folder {folder_name}:")
    
    for filename in os.listdir(folder_name):
        if filename.endswith(".png"):
            file_path = os.path.join(folder_name, filename)
            image = Image.open(file_path)
            
            # Armazene a imagem no dicionário, usando o nome do arquivo como chave
            images[filename] = image
            
            print(f"Imagem lida: {filename}")
    
    return images

# Lista de nomes de pastas
folders = ["GreyBackground", "WhiteBackground", "IntrinsicCalibration"]

# Dicionário para armazenar as imagens
image_arrays = {}

# Para cada pasta, chame a função ler_imagens_de_pasta e armazene o resultado no dicionário image_arrays
for folder_name in folders:
    image_arrays[f"array_{folder_name}"] = ler_imagens_de_pasta(folder_name)
    print("")

# Agora você tem dicionários separados para cada pasta com o nome da pasta como chave
print(image_arrays["array_GreyBackground"])
print(image_arrays["array_WhiteBackground"])
print(image_arrays["array_IntrinsicCalibration"])

Imagens do folder GreyBackground:
Imagem lida: calib_img 0.png
Imagem lida: calib_img 1.png
Imagem lida: calib_img 2.png
Imagem lida: calib_img 3.png
Imagem lida: calib_img 4.png
Imagem lida: calib_img 5.png
Imagem lida: extrinsic.png

Imagens do folder WhiteBackground:
Imagem lida: calib_img 0.png
Imagem lida: calib_img 1.png
Imagem lida: calib_img 2.png
Imagem lida: calib_img 3.png
Imagem lida: extrinsic.png

Imagens do folder IntrinsicCalibration:
Imagem lida: calib_img 0.png
Imagem lida: calib_img 1.png
Imagem lida: calib_img 10.png
Imagem lida: calib_img 11.png
Imagem lida: calib_img 12.png
Imagem lida: calib_img 13.png
Imagem lida: calib_img 14.png
Imagem lida: calib_img 15.png
Imagem lida: calib_img 16.png
Imagem lida: calib_img 17.png
Imagem lida: calib_img 18.png
Imagem lida: calib_img 19.png
Imagem lida: calib_img 2.png
Imagem lida: calib_img 20.png
Imagem lida: calib_img 21.png
Imagem lida: calib_img 22.png
Imagem lida: calib_img 23.png
Imagem lida: calib_img 24.png
Imagem l

<h1> Exercises Resolution </h1>

<h2> 1. Calibrate the intrinsic parameters and lens distortion of the camera. Show the intrinsic matrix and the lens distortion coefficients. </h2>

In [20]:
# Dicionário com imagens
intrinsicimages = image_arrays["array_IntrinsicCalibration"]
intrinsicimages

{'calib_img 0.png': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1920x1080>,
 'calib_img 1.png': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1920x1080>,
 'calib_img 10.png': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1920x1080>,
 'calib_img 11.png': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1920x1080>,
 'calib_img 12.png': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1920x1080>,
 'calib_img 13.png': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1920x1080>,
 'calib_img 14.png': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1920x1080>,
 'calib_img 15.png': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1920x1080>,
 'calib_img 16.png': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1920x1080>,
 'calib_img 17.png': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1920x1080>,
 'calib_img 18.png': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1920x1080>,
 'calib_img 19.png': <PIL.PngImagePlugin.PngImageFil

In [24]:

import glob
# Converte imagens PNG em JPEG
input_folder = "IntrinsicCalibration/"
output_folder = "IntrinsicCalibration/"

# Certifique-se de que a pasta de saída exista
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

for filename in os.listdir(input_folder):
    if filename.endswith(".png"):
        image = cv2.imread(os.path.join(input_folder, filename))
        output_filename = os.path.splitext(filename)[0] + ".jpg"
        output_path = os.path.join(output_folder, output_filename)
        cv2.imwrite(output_path, image)

# Prossiga com a calibração da câmera
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
objp = np.zeros((6 * 7, 3), np.float32)
objp[:, :2] = np.mgrid[0:7, 0:6].T.reshape(-1, 2)
objpoints = []
imgpoints = []

images = glob.glob(os.path.join(output_folder, '*.jpg'))

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(gray, (7, 6), None)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

        cv2.drawChessboardCorners(img, (7, 6), corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(500)

cv2.destroyAllWindows()

# Calibração da câmera
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3752: error: (-215:Assertion failed) nimages > 0 in function 'cv::calibrateCameraRO'


In [11]:
# Recupere as imagens da pasta "IntrinsicCalibration"
image_array = image_arrays["array_IntrinsicCalibration"]

# Defina o tamanho do tabuleiro de xadrez (número de interseções internas)
chessboard_size = (8, 5)  # Substitua pelo tamanho do tabuleiro de xadrez usado

# Listas para armazenar pontos de correspondência em 3D (pontos do mundo real) e 2D (pontos na imagem)
object_points = []  # 3D
image_points = []   # 2D

# Crie um grid de pontos no espaço 3D (pontos do mundo real)
object_points_grid = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
object_points_grid[:, :2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2)

for image in image_array.values():
    gray = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2GRAY)

    # Tente encontrar os cantos do tabuleiro de xadrez na imagem
    ret, corners = cv2.findChessboardCorners(gray, chessboard_size, None)

    if ret:
        object_points.append(object_points_grid)
        image_points.append(corners)

# Calibrar a câmera
ret, intrinsic_matrix, distortion_coefficients, rvecs, tvecs = cv2.calibrateCamera(object_points, image_points, gray.shape[::-1], None, None)

if ret:
    print("Calibração concluída com sucesso:")
    print("Matriz intrínseca (câmera):")
    print(intrinsic_matrix)
    print("\nCoeficientes de distorção da lente:")
    print(distortion_coefficients)
else:
    print("A calibração falhou.")

error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3752: error: (-215:Assertion failed) nimages > 0 in function 'cv::calibrateCameraRO'


In [16]:
# Recupere as imagens da pasta "IntrinsicCalibration"
image_array = image_arrays["array_IntrinsicCalibration"]

# Prepare object points for a 5x8 chessboard
chessboard_size = (5,8)  # 8 colunas e 5 linhas
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objp = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[1], 0:chessboard_size[0]].T.reshape(-1, 2)

# Arrays to store object points and image points from all the images
objpoints = []  # 3D points in real-world space
imgpoints = []  # 2D points in image plane

# Loop through the images in image_array
for image in image_array.values():
    img = np.array(image)
    print(img)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, chessboard_size, None)

    # If found, add object points, image points (after refining them)
    if ret:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

        # Draw and display the corners
        img_with_corners = cv2.drawChessboardCorners(img, chessboard_size, corners2, ret)
        cv2.imshow('img', img_with_corners)
        cv2.waitKey(500)

# Calibration of the camera
ret, intrinsic_matrix, distortion_coefficients, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

if ret:
    print("Calibração concluída com sucesso:")
    print("Matriz intrínseca (câmera):")
    print(intrinsic_matrix)
    print("\nCoeficientes de distorção da lente:")
    print(distortion_coefficients)
else:
    print("A calibração falhou.")

cv2.destroyAllWindows()

error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3752: error: (-215:Assertion failed) nimages > 0 in function 'cv::calibrateCameraRO'


In [30]:
# Recupere as imagens da pasta "IntrinsicCalibration"
image_array = image_arrays["array_IntrinsicCalibration"]

# Prepare object points for a 5x8 chessboard
chessboard_size = (5,8)  # 8 colunas e 5 linhas
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objp = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[1], 0:chessboard_size[0]].T.reshape(-1, 2)

# Arrays to store object points and image points from all the images
objpoints = []  # 3D points in real-world space
imgpoints = []  # 2D points in image plane

# Loop through the images in image_array
for fname in image_array:
    print(fname)
    img = cv2.imread(fname)
    cv2.imshow(img)
    print(img)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, chessboard_size, None)

    # If found, add object points, image points (after refining them)
    if ret:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        imgpoints.append(corners2)

calib_img 0.png


NameError: name 'cv2_imshow' is not defined

In [48]:
img = cv2.imread('IntrinsicCalibration/calib_img 0.png')
print(img.shape)
print(img.dtype)
print(img)
#print(img)
#cv2.imshow('Imagem', img)

print("")


gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(gray.shape)
print(gray.dtype)
print(gray)
final_frame = cv2.hconcat((img, gray))
cv2.imshow(final_frame)
# Find the chessboard corners
ret, corners = cv2.findChessboardCorners(gray, (8,5), None)

# If found, add object points, image points (after refining them)
if ret:
    print("Entrei")
    objpoints.append(objp)
    corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
    imgpoints.append(corners2)

(1080, 1920, 3)
uint8
[[[ 34  47  42]
  [ 37  50  45]
  [ 40  53  48]
  ...
  [  8  30  46]
  [ 74 101 116]
  [ 90 117 132]]

 [[ 35  48  43]
  [ 37  50  45]
  [ 40  53  48]
  ...
  [  9  31  47]
  [ 71  98 113]
  [ 88 115 130]]

 [[ 38  49  42]
  [ 40  51  44]
  [ 42  53  46]
  ...
  [ 12  34  52]
  [ 66  90 108]
  [ 86 110 128]]

 ...

 [[ 39  54  50]
  [ 40  53  49]
  [ 41  52  47]
  ...
  [113 161 188]
  [106 154 181]
  [107 155 182]]

 [[ 42  56  55]
  [ 36  48  47]
  [ 37  47  44]
  ...
  [104 154 180]
  [101 153 179]
  [ 98 150 176]]

 [[ 35  49  48]
  [ 40  52  51]
  [ 45  55  52]
  ...
  [101 151 177]
  [101 153 179]
  [105 157 183]]]

(1080, 1920)
uint8
[[ 44  47  50 ...  32 102 118]
 [ 45  47  50 ...  33  99 116]
 [ 46  48  50 ...  37  93 113]
 ...
 [ 51  50  49 ... 164 157 158]
 [ 54  46  45 ... 156 155 152]
 [ 47  50  53 ... 153 155 159]]


error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\core\src\matrix_operations.cpp:67: error: (-215:Assertion failed) src[i].dims <= 2 && src[i].rows == src[0].rows && src[i].type() == src[0].type() in function 'cv::hconcat'


<h2> 2. Calibrate the extrinsic parameters of the camera setup (or instead, use 
the  extrinsic  image  to  manually  measure  the  dimensions  of  a  black 
square  of  the  chessboard  in  pixels.  In  this  way,  you  will  know  the 
conversion between pixel to millimeter). Show the extrinsic matrix 
(rotation,  translation,  etc)  and/or  the  conversion  ratio  between  pixel  to 
millimeter that was used.  </h2>

<h2> 3. Consider only the images retrieved from a White Background. Implement the functions described above. </h2>

In [16]:
# Dicionário com imagens
whiteimages = image_arrays["array_WhiteBackground"]

<h3> 3.1 Define a ROI (region of interest) for the image </h3> 

In [ ]:
def define_roi(image, x, y, width, height):
    roi = image.crop((x, y, x + width, y + height))
    return roi

In [10]:
# Exemplo de uso:
x = 100
y = 150
width = 200
height = 150

# Iterar por todas as imagens e criar ROI para cada uma
roi_images = {}
for image_name, image in whiteimages.items():
    roi = define_roi(image, x, y, width, height)
    roi.show()
    roi_images[image_name] = roi

<h3> 3.2 Calculate the number of M&M per color for all images provided </h3>

In [11]:
def count_mms_by_color(image, color_masks):
    hsv_image = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
    counts = {}
    for color, mask in color_masks.items():
        result = cv2.bitwise_and(image, image, mask=mask)
        mms_count = np.sum(mask > 0) // 255
        counts[color] = mms_count
    return counts

In [17]:
# Suponha que whiteimages seja o seu dicionário de imagens
color_counts = {}  # Dicionário para armazenar a contagem de M&Ms por cor

for image_name, image in whiteimages.items():
    # Carregue a imagem em formato RGB (por exemplo, utilizando PIL)
    image_rgb = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)

    # Converta a imagem BGR para o espaço de cores HSV
    hsv_image = cv2.cvtColor(image_rgb, cv2.COLOR_BGR2HSV)

    # Defina os intervalos de cor para M&M amarelo
    lower_yellow = np.array([20, 100, 100])
    upper_yellow = np.array([30, 255, 255])

    # Defina os intervalos de cor para M&M azul
    lower_blue = np.array([90, 50, 50])
    upper_blue = np.array([130, 255, 255])

    # Defina os intervalos de cor para M&M vermelho
    lower_red1 = np.array([0, 100, 100])
    upper_red1 = np.array([10, 255, 255])
    lower_red2 = np.array([160, 100, 100])
    upper_red2 = np.array([180, 255, 255])

    # Defina os intervalos de cor para M&M verde
    lower_green = np.array([40, 100, 100])
    upper_green = np.array([80, 255, 255])

    color_masks = {
        "Yellow": cv2.inRange(hsv_image, lower_yellow, upper_yellow),
        "Blue": cv2.inRange(hsv_image, lower_blue, upper_blue),
        "Red": cv2.inRange(hsv_image, lower_red1, upper_red1) | cv2.inRange(hsv_image, lower_red2, upper_red2),
        "Green": cv2.inRange(hsv_image, lower_green, upper_green)
    }

    # Conte o número de M&M por cor na imagem atual
    counts = count_mms_by_color(hsv_image, color_masks)
    
    color_counts[image_name] = counts

In [18]:
color_counts

{'calib_img 0.png': {'Yellow': 23, 'Blue': 31, 'Red': 0, 'Green': 0},
 'calib_img 1.png': {'Yellow': 168, 'Blue': 195, 'Red': 0, 'Green': 0},
 'calib_img 2.png': {'Yellow': 154, 'Blue': 244, 'Red': 106, 'Green': 0},
 'calib_img 3.png': {'Yellow': 144, 'Blue': 1106, 'Red': 102, 'Green': 31},
 'extrinsic.png': {'Yellow': 6, 'Blue': 71, 'Red': 0, 'Green': 0}}

<h3> 3.3 Determine the average area for peanuts in pixels, considering the 
image “calib_img 3” </h3>

<h4> 3.3.1 Show all peanuts that were detected </h4>

<h4> 3.3.2 Discuss the limitations of the peanut detection method used (in 2 sentences) </h4>

<h3> 3.4 Determine the average area (and standard deviation) for peanuts 
in millimeters and grouped by color, considering images “calib_img 
2” and “calib_img 3” </h3>

<h4> 3.4.1 Show  the  result  in  a  table  color  vs  area  and  standard deviation </h4>

<h4> 3.4.2 Discuss  the  limitation  of  the  method  implemented  (in  2 sentences) </h4>

<h3> 3.5 Provide some recommendations that the M&M factory should take 
into  consideration to  improve  the  performance  of  the quality 
assurance  process  based  on  image  processing  (e.g.,  imaging 
setup, calibration process and photometric effects), in 4 sentences. </h3>